### ISSUE TITLE
Plan Volunteer Photo

### ISSUE THREAD

**Issue by Adimote** [srobo/sr2023-comp#8]

**Comment by PeterJCLaw** [comment]
@Adimote is this on the right repo? Did you mean to put this on the compstate, or should it be on https://github.com/srobo/tasks?

**Comment by PeterJCLaw** [comment]
Looks like maybe this can be closed in favour of https://github.com/srobo/tasks/issues/1171?

**Comment by Adimote** [comment]
yes, I thought I clicked the close button after accidentally creating this. Now actually closed.
